[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "chatatp-cli"
version = "1.0.9"
description = "ChatATP CLI - Terminal Interface for ChatATP API"
readme = "README.md"
authors = [
    { name = "ChatATP Team", email = "support@chatatp.com" }
]

classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Operating System :: OS Independent",
  "Topic :: Software Development :: Libraries :: Python Modules",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
  "Topic :: Internet :: WWW/HTTP",
  "Topic :: Communications :: Chat",
  "Topic :: Software Development :: Libraries :: Application Frameworks",
]
keywords = [
  "agent",
  "toolkit",
  "chat",
  "sdk",
  "llm",
  "ChatATP",
  "ChatGPT",
  "AI Agent Frameworks",
  "websocket",
  "http",
  "api",
  "tools",
  "functions",
  "automation",
  "ATP",
  "Agent Tool Protocol",
  "ATP SDK",
  "tool registration",
  "tool invocation",
  "tool serving",
  "toolkit registration",
  "toolkit invocation",
  "toolkit serving",
  "remote tool invocation",
  "remote tool serving",
  "remote tool registration",
  "remote toolkit invocation",
  "Samuel Obinna Chimdi",
  "ChatATP Agent",
  "ChatATP CLI",
  "ChatATP Python CLI",
  "ChatATP Python Command Line Interface",
]

dependencies = [
    "requests",
    "click",
    "rich",
    "pyyaml",
    "python-dotenv",
]

[project.scripts]
chatatp = "chatatp_cli.main:cli"

[project.urls]
Homepage = "https://chat-atp.com"
Documentation = "https://docs.chat-atp.com"
Repository = "https://github.com/sam-14uel/ChatATP-Python-Cli"
Issues = "https://github.com/sam-14uel/ChatATP-Python-Cli/issues"

